# Generated by Django 4.2.7 on 2025-06-03 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("journal_streak", "Journal Streak"),
                            ("mood_improvement", "Mood Improvement"),
                            ("coping_skill", "Coping Skill Learned"),
                            ("therapy_session", "Therapy Session"),
                            ("goal_achieved", "Goal Achieved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-achieved_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-achieved_at"],
                        name="progress_us_user_id_8f6bb3_idx",
                    ),
                    models.Index(
                        fields=["milestone_type"], name="progress_us_milesto_977f50_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgressOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_journal_entries", models.IntegerField(default=0)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("milestones_achieved", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("stats", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="progress_pr_user_id_75fa20_idx")
                ],
            },
        ),
    ]
