# Generated by Django 4.2.7 on 2025-05-26 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journalanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="journalanalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="analysis_jo_user_id_0c10cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalanalysis",
            index=models.Index(
                fields=["risk_level"], name="analysis_jo_risk_le_b7cab5_idx"
            ),
        ),
    ]
