# Generated by Django 4.2.7 on 2025-05-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalanalysis",
            name="analysis_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalanalysis",
            name="analysis_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
