# Generated by Django 4.2.7 on 2025-05-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_remove_journal_mood_score_journal_after_mood_and_more"),
        ("analysis", "0003_journalanalysis_analysis_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalanalysis",
            name="journal",
            field=models.OneToOneField(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="journal.journal",
            ),
            preserve_default=False,
        ),
    ]
