# Generated by Django 4.2.7 on 2025-05-30 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_dailymood"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="mood_score",
        ),
        migrations.AddField(
            model_name="journal",
            name="after_mood",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="before_mood",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
