# Generated by Django 4.2.7 on 2025-05-26 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("milestone", models.CharField(max_length=100)),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-achieved_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-achieved_at"],
                        name="users_userp_user_id_92c61f_idx",
                    ),
                    models.Index(
                        fields=["milestone"], name="users_userp_milesto_0694a7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=50)),
                ("bio", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("preferences", models.JSONField(default=dict)),
                ("notification_settings", models.JSONField(default=dict)),
                ("privacy_settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="users_userp_user_id_d181df_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="OnboardingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("steps_completed", models.JSONField(default=dict)),
                ("last_step", models.CharField(blank=True, max_length=50)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(fields=["user"], name="users_onboa_user_id_4ce12a_idx")
                ],
            },
        ),
    ]
